package com.ghuljr.sharebox.ui.utils

fun loremIpsum(): String = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam in ante dictum, imperdiet eros vitae, feugiat elit. Nam consectetur rhoncus nisl id molestie. Praesent porttitor massa eget tortor fermentum cursus. Vestibulum eu tortor nec justo bibendum mattis. Duis metus nisl, aliquet at eros et, laoreet commodo lectus. Donec sagittis non tortor id semper. Maecenas quam ipsum, dignissim nec tincidunt non, volutpat nec turpis. Donec at enim sit amet lacus rutrum consequat eu a tellus.\n" +
        "\n" +
        "Fusce lorem est, aliquet et pulvinar vitae, semper eget erat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In luctus ornare lacus vel placerat. Integer a semper ligula. Donec dictum ultricies ante ac volutpat. Morbi posuere tempor tortor id fermentum. Nullam et nisi dictum, hendrerit dolor a, condimentum felis. Mauris vel ultrices sem. Integer aliquet id leo vel iaculis. Aenean ultrices venenatis accumsan. Aenean id elit sodales, varius nunc vitae, euismod nulla.\n" +
        "\n" +
        "Nam id magna ut ipsum bibendum interdum viverra eu turpis. Aliquam eget sapien congue eros tincidunt ultrices. Quisque ac lectus ante. Ut a magna at metus vehicula suscipit non ac risus. Donec non lacus ultricies, mattis purus vitae, tristique ipsum. Pellentesque nec rhoncus tellus. Suspendisse id ipsum mauris. Donec maximus lacus et condimentum luctus. Fusce ultricies nulla lacus, at finibus magna sollicitudin quis. Vestibulum semper ligula nec tortor egestas commodo. Sed maximus, felis non elementum ultrices, magna odio maximus nulla, eget lacinia sapien ipsum in neque. Phasellus bibendum tortor non massa tempor laoreet.\n" +
        "\n" +
        "Mauris quis mauris arcu. Duis eget diam quis nisl mattis tincidunt. Phasellus vitae lectus et mauris sodales tristique. Curabitur tristique metus nisl, id elementum erat pharetra non. Maecenas et feugiat augue. Proin vitae suscipit diam. Aenean interdum, nunc eget fermentum sodales, elit tortor convallis urna, eu pellentesque erat risus at massa. Vestibulum ac semper erat. Praesent luctus, nisl in gravida viverra, erat tortor efficitur ex, ut convallis est sapien sed sem. Integer lorem magna, scelerisque eget lacinia ac, vestibulum eu enim.\n" +
        "\n" +
        "Morbi tincidunt enim sed lectus laoreet ultrices. Duis sed dignissim nulla. Vestibulum in dui at tortor consectetur euismod ac mollis enim. Quisque aliquet pulvinar sapien, sed mattis dui pharetra quis. Aenean risus turpis, euismod non placerat et, rutrum sit amet eros. Nunc tincidunt tincidunt mi, eu dapibus est blandit ac. In ultricies augue non scelerisque aliquam. Maecenas eget ullamcorper metus, eget interdum nunc. In non velit accumsan, hendrerit mauris ut, placerat neque. Nam placerat gravida varius. Morbi mauris lorem, hendrerit vel orci ac, bibendum rutrum lacus.\n" +
        "\n" +
        "Pellentesque mi turpis, efficitur ac porta sed, eleifend eget tellus. Aenean dignissim maximus mauris ut ultrices. Pellentesque lobortis, elit id venenatis interdum, nunc turpis lobortis ante, eu feugiat mauris ipsum id nisl. Mauris massa nisi, suscipit sed orci vitae, sodales ornare elit. Maecenas efficitur lorem eu justo pellentesque, a auctor purus lacinia. Donec cursus scelerisque tempor. Nulla pharetra mauris eu malesuada pellentesque. Morbi eros tellus, mollis ac ex ac, fringilla viverra nibh. Phasellus tristique orci nisi, a bibendum nibh aliquet et. Praesent in condimentum sem. Nulla lorem lorem, aliquam et lacinia at, pulvinar ut lectus. Ut consectetur tellus a turpis pellentesque sollicitudin in in urna. Aenean ut turpis vulputate, ornare nibh vel, gravida libero.\n" +
        "\n" +
        "Aliquam dictum lectus ac mauris mollis, eget condimentum augue tristique. Pellentesque bibendum accumsan porta. Quisque sit amet velit non purus elementum ultricies vitae a dui. Nam eu fringilla tellus, ac porttitor ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam id laoreet orci. Suspendisse imperdiet, est hendrerit iaculis tempus, metus augue porta massa, eget auctor diam nisl sit amet elit. Praesent imperdiet, nibh in aliquet mollis, nulla ipsum pharetra nunc, a consectetur dui sem sit amet odio. Morbi varius risus a sapien tempor, sed maximus felis commodo. Morbi vel eros odio. Nulla at leo a arcu dictum rhoncus sed eget risus. Sed cursus augue lacus. Donec quis posuere nibh, a convallis elit. Mauris neque ligula, volutpat nec lectus sit amet, tempus lacinia arcu. Fusce eu augue eget est viverra egestas.\n" +
        "\n" +
        "In at mattis ante. Sed laoreet orci ut purus gravida ultricies. Integer quis tempor nulla, sed viverra metus. Aliquam blandit mi non quam sollicitudin, vitae dictum nisi sollicitudin. Curabitur et ipsum sit amet nulla porttitor tempor. Sed ultricies ex sit amet metus efficitur laoreet. Etiam efficitur ipsum ut tristique dictum. Integer eu nibh vel arcu lacinia gravida. Mauris sodales augue eget congue maximus. Ut faucibus neque ac nisl placerat facilisis. Vestibulum nec pellentesque libero. Etiam at est quis nisi tincidunt ultricies. Aenean scelerisque imperdiet pellentesque. In massa nisi, mollis eget dapibus quis, egestas et est. Maecenas dapibus quam nisi, nec faucibus magna aliquam vitae.\n" +
        "\n" +
        "Aenean sed ex bibendum, tincidunt augue ac, fermentum justo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc rhoncus velit enim, in facilisis enim semper eu. In dapibus nunc id cursus auctor. Pellentesque id mauris rhoncus, ultricies lorem vel, posuere diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque sit amet justo tempus, iaculis libero sit amet, facilisis metus. Aliquam ut dictum nunc, et viverra sapien. Aenean interdum diam vel ante eleifend, in blandit mi sagittis.\n" +
        "\n" +
        "Aliquam consequat nec massa sit amet faucibus. Aenean rutrum lectus vel varius dignissim. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam erat volutpat. Mauris eget molestie lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras in imperdiet tortor. Vivamus at nisl convallis, fringilla arcu nec, hendrerit lorem. Duis ut magna id odio ultricies pulvinar. Curabitur tempor efficitur risus vitae imperdiet. Duis semper erat sit amet risus viverra, ac pharetra arcu bibendum.\n" +
        "\n" +
        "Duis tempus posuere tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam ac sollicitudin urna. Suspendisse ornare dictum justo, eget vestibulum enim ultrices eu. Nunc mollis turpis dui, in blandit nunc sagittis ac. Vivamus auctor erat a imperdiet euismod. Aenean facilisis tellus arcu, id posuere dui varius at. Fusce luctus rhoncus nisi, nec volutpat mi dapibus nec. Fusce ut erat massa. Duis mattis interdum ligula, vulputate varius tellus."